### ISSUE TITLE
the code is infinitly running

### ISSUE THREAD

**Issue by rawanateya** [PeachyVVolf/GA-Sudoku-Puzzle#1]
the code doesn't have an end. it just keeps running and running.

**Comment by PeachyVVolf** [comment]
Yes, it does keep running infinitely. Because it never finds the exact solution. It does get very very close to the optimal solution but it doesn't find the exact answer. You could add a limit on the loop. It ends if it finds the exact answer, if not, then the loop would end even if it doesn't find the exact answer. So for example, after 10000 iterations you would have a solution pretty close to the exact answer. 
Also if you decide to change something or make it work better (this is ok just needs to be optimized). Then let me give you an overview because back when i made this, i didn't understand the importance of documents. Anyways, this checks the first row and counts if all values are different. If all rows indexes have unique values then it adds to a variable. So 9(9 indexes)*9(9 rows) = 81. Then it checks all the columns. So, 81(row score) + 9(9 indexes in one columns) * 9(9 columns) = 162 . Then the boxes. 162 + (9*9) = 243. This is the optimal score. My code gets to at most 237.

I hope that explains everything. If you have any more questions, do let  me know.
